{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1557", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1557/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1557/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1557/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/1557", "id": 1669332775, "node_id": "I_kwDOJKSTjM5jf_8n", "number": 1557, "title": " Command execute_local_command returned: Unknown command 'execute_local_command'.", "user": {"login": "xiaoqiangch", "id": 16594186, "node_id": "MDQ6VXNlcjE2NTk0MTg2", "avatar_url": "https://avatars.githubusercontent.com/u/16594186?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xiaoqiangch", "html_url": "https://github.com/xiaoqiangch", "followers_url": "https://api.github.com/users/xiaoqiangch/followers", "following_url": "https://api.github.com/users/xiaoqiangch/following{/other_user}", "gists_url": "https://api.github.com/users/xiaoqiangch/gists{/gist_id}", "starred_url": "https://api.github.com/users/xiaoqiangch/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xiaoqiangch/subscriptions", "organizations_url": "https://api.github.com/users/xiaoqiangch/orgs", "repos_url": "https://api.github.com/users/xiaoqiangch/repos", "events_url": "https://api.github.com/users/xiaoqiangch/events{/privacy}", "received_events_url": "https://api.github.com/users/xiaoqiangch/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2023-04-15T12:05:34Z", "updated_at": "2023-04-30T10:26:08Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "I have got this feed back:\r\n\r\n2023-04-15 15:39:14,325 INFO Apparently json was fixed.\r\n2023-04-15 15:39:14,495 INFO NEXT ACTION:  COMMAND = execute_local_command  ARGUMENTS = {'command_line': 'mkdir -p ~/.obsidian/plugins/chatgp-plugin && touch ~/.obsidian/plugins/chatgp-plugin/main.js'}\r\n2023-04-15 15:39:21,634 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=\r\n2023-04-15 15:39:22,291 INFO SYSTEM:  Command execute_local_command returned: Unknown command 'execute_local_command'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.\r\n\r\n\r\nand the program kind of stuck in a loop, the shell command was not executed.\r\n\r\nany ideas for solving this issue? thanks a lot.\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1557/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1557/timeline", "performed_via_github_app": null, "state_reason": null}