{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/285", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/285/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/285/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/285/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/pull/285", "id": 1656534763, "node_id": "PR_kwDOJKSTjM5NuXaZ", "number": 285, "title": "Fixed Json Error", "user": {"login": "jetblaise", "id": 29067169, "node_id": "MDQ6VXNlcjI5MDY3MTY5", "avatar_url": "https://avatars.githubusercontent.com/u/29067169?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jetblaise", "html_url": "https://github.com/jetblaise", "followers_url": "https://api.github.com/users/jetblaise/followers", "following_url": "https://api.github.com/users/jetblaise/following{/other_user}", "gists_url": "https://api.github.com/users/jetblaise/gists{/gist_id}", "starred_url": "https://api.github.com/users/jetblaise/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jetblaise/subscriptions", "organizations_url": "https://api.github.com/users/jetblaise/orgs", "repos_url": "https://api.github.com/users/jetblaise/repos", "events_url": "https://api.github.com/users/jetblaise/events{/privacy}", "received_events_url": "https://api.github.com/users/jetblaise/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5272676262, "node_id": "LA_kwDOJKSTjM8AAAABOkanpg", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/question", "name": "question", "color": "d876e3", "default": true, "description": "Further information is requested"}, {"id": 5400185961, "node_id": "LA_kwDOJKSTjM8AAAABQeBMaQ", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/conflicts", "name": "conflicts", "color": "FBCA04", "default": false, "description": "Automatically applied to PRs with merge conflicts"}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2023-04-06T01:35:00Z", "updated_at": "2023-04-22T23:26:10Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "draft": false, "pull_request": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/pulls/285", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/pull/285", "diff_url": "https://github.com/Significant-Gravitas/Auto-GPT/pull/285.diff", "patch_url": "https://github.com/Significant-Gravitas/Auto-GPT/pull/285.patch", "merged_at": null}, "body": "Fixed the json_parser.py error by making chatgpt fix itself\r\n\r\ndef fix_and_parse_json(json_str: str, try_to_fix_with_gpt: bool = True):\r\n    json_schema = \"\"\"\r\n    {\r\n    \"command\": {\r\n        \"name\": \"command name\",\r\n        \"args\":{\r\n            \"arg name\": \"value\"\r\n        }\r\n    },\r\n    \"thoughts\":\r\n    {\r\n        \"text\": \"thought\",\r\n        \"reasoning\": \"reasoning\",\r\n        \"plan\": \"- short bulleted\\n- list that conveys\\n- long-term plan\",\r\n        \"criticism\": \"constructive self-criticism\",\r\n        \"speak\": \"thoughts summary to say to user\"\r\n    }\r\n    }\r\n    \"\"\"\r\n\r\n    def clean_input(json_str):\r\n        brace_index = json_str.index(\"{\")\r\n        json_str = json_str[brace_index:]\r\n        last_brace_index = json_str.rindex(\"}\")\r\n        json_str = json_str[:last_brace_index+1]\r\n        return json_str\r\n\r\n    def attempt_parse(json_str):\r\n        try:\r\n            return json.loads(json_str)\r\n        except Exception as e:\r\n            return None\r\n\r\n    cleaned_json_str = clean_input(json_str)\r\n    parsed_json = attempt_parse(cleaned_json_str)\r\n\r\n    if parsed_json is not None:\r\n        return parsed_json\r\n    elif try_to_fix_with_gpt:\r\n        print(\"Warning: Failed to parse AI output, attempting to fix.\")\r\n        ai_fixed_json = fix_json(cleaned_json_str, json_schema, False)\r\n\r\n        if ai_fixed_json != \"failed\":\r\n            return json.loads(ai_fixed_json)\r\n        else:\r\n            print(\"Failed to fix ai output, telling the AI.\")\r\n            return json_str\r\n\r\n    raise ValueError(\"Failed to parse JSON: '{}'\".format(json_str))", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/285/reactions", "total_count": 2, "+1": 2, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/285/timeline", "performed_via_github_app": null, "state_reason": null}