{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3054", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3054/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3054/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3054/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/3054", "id": 1680152555, "node_id": "I_kwDOJKSTjM5kJRfr", "number": 3054, "title": "Pinecone", "user": {"login": "Xerizaf", "id": 109890020, "node_id": "U_kgDOBozJ5A", "avatar_url": "https://avatars.githubusercontent.com/u/109890020?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Xerizaf", "html_url": "https://github.com/Xerizaf", "followers_url": "https://api.github.com/users/Xerizaf/followers", "following_url": "https://api.github.com/users/Xerizaf/following{/other_user}", "gists_url": "https://api.github.com/users/Xerizaf/gists{/gist_id}", "starred_url": "https://api.github.com/users/Xerizaf/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Xerizaf/subscriptions", "organizations_url": "https://api.github.com/users/Xerizaf/orgs", "repos_url": "https://api.github.com/users/Xerizaf/repos", "events_url": "https://api.github.com/users/Xerizaf/events{/privacy}", "received_events_url": "https://api.github.com/users/Xerizaf/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 5347563882, "node_id": "LA_kwDOJKSTjM8AAAABPr1Zag", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/setup", "name": "setup", "color": "E1BC6F", "default": false, "description": "Issues with getting Auto-GPT setup on local machines"}, {"id": 5409160395, "node_id": "LA_kwDOJKSTjM8AAAABQmk8yw", "url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/labels/function:%20memory", "name": "function: memory", "color": "E12F75", "default": false, "description": ""}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2023-04-23T20:09:39Z", "updated_at": "2023-04-25T07:59:33Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### \u26a0\ufe0f Search for existing issues first \u26a0\ufe0f\n\n- [X] I have searched the existing issues, and there is no existing issue for my problem\n\n### Which Operating System are you using?\n\nWindows\n\n### Which version of Auto-GPT are you using?\n\nLatest Release\n\n### GPT-3 or GPT-4?\n\nGPT-3.5\n\n### Steps to reproduce \ud83d\udd79\n\nRun the program\n\n### Current behavior \ud83d\ude2f\n\nTraceback (most recent call last):\r\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"C:\\Users\\aless\\OneDrive\\Desktop\\Auto-GPT\\autogpt\\__main__.py\", line 5, in <module>\r\n    autogpt.cli.main()\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\click\\core.py\", line 1130, in __call__\r\n    return self.main(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\click\\core.py\", line 1055, in main\r\n    rv = self.invoke(ctx)\r\n         ^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\click\\core.py\", line 1635, in invoke\r\n    rv = super().invoke(ctx)\r\n         ^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\click\\core.py\", line 1404, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\click\\core.py\", line 760, in invoke\r\n    return __callback(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\click\\decorators.py\", line 26, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\OneDrive\\Desktop\\Auto-GPT\\autogpt\\cli.py\", line 77, in main\r\n    from autogpt.agent.agent import Agent\r\n  File \"C:\\Users\\aless\\OneDrive\\Desktop\\Auto-GPT\\autogpt\\agent\\__init__.py\", line 1, in <module>\r\n    from autogpt.agent.agent import Agent\r\n  File \"C:\\Users\\aless\\OneDrive\\Desktop\\Auto-GPT\\autogpt\\agent\\agent.py\", line 3, in <module>\r\n    from autogpt.app import execute_command, get_command\r\n  File \"C:\\Users\\aless\\OneDrive\\Desktop\\Auto-GPT\\autogpt\\app.py\", line 26, in <module>\r\n    from autogpt.commands.web_requests import scrape_links, scrape_text\r\n  File \"C:\\Users\\aless\\OneDrive\\Desktop\\Auto-GPT\\autogpt\\commands\\web_requests.py\", line 16, in <module>\r\n    memory = get_memory(CFG)\r\n             ^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\OneDrive\\Desktop\\Auto-GPT\\autogpt\\memory\\__init__.py\", line 50, in get_memory\r\n    memory = PineconeMemory(cfg)\r\n             ^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\OneDrive\\Desktop\\Auto-GPT\\autogpt\\config\\singleton.py\", line 15, in __call__\r\n    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)\r\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\OneDrive\\Desktop\\Auto-GPT\\autogpt\\memory\\pinecone.py\", line 41, in __init__\r\n    pinecone.create_index(\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pinecone\\manage.py\", line 118, in create_index\r\n    api_instance.create_index(create_request=CreateRequest(\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pinecone\\core\\client\\api_client.py\", line 776, in __call__\r\n    return self.callable(self, *args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pinecone\\core\\client\\api\\index_operations_api.py\", line 370, in __create_index      \r\n    return self.call_with_http_info(**kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pinecone\\core\\client\\api_client.py\", line 838, in call_with_http_info\r\n    return self.api_client.call_api(\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pinecone\\core\\client\\api_client.py\", line 413, in call_api\r\n    return self.__call_api(resource_path, method,\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pinecone\\core\\client\\api_client.py\", line 207, in __call_api\r\n    raise e\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pinecone\\core\\client\\api_client.py\", line 200, in __call_api\r\n    response_data = self.request(\r\n                    ^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pinecone\\core\\client\\api_client.py\", line 459, in request\r\n    return self.rest_client.POST(url,\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pinecone\\core\\client\\rest.py\", line 271, in POST\r\n    return self.request(\"POST\", url,\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\aless\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pinecone\\core\\client\\rest.py\", line 230, in request\r\n    raise ApiException(http_resp=r)\r\npinecone.core.client.exceptions.ApiException: (400)\r\nReason: Bad Request\r\nHTTP response headers: HTTPHeaderDict({'content-type': 'text/plain; charset=UTF-8', 'date': 'Sun, 23 Apr 2023 20:00:05 GMT', 'x-envoy-upstream-service-time': '1333', 'content-length': '131', 'server': 'envoy'})\r\nHTTP response body: The index exceeds the project quota of 1 pods by 1 pods. Upgrade your account or change the project settings to increase the quota.\n\n### Expected behavior \ud83e\udd14\n\nTo work properly\n\n### Your prompt \ud83d\udcdd\n\n```yaml\r\n# Paste your prompt here\r\n```\r\n\n\n### Your Logs \ud83d\udcd2\n\n```log\r\n<insert your logs here>\r\n```\r\n2023-04-23 21:45:01,283 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= \r\n2023-04-23 21:45:03,227 INFO SYSTEM:  Command google returned: [\r\n    {\r\n        \"title\": \"The Current State of Dragon Ball Legends - 2nd Anniversary\",\r\n        \"href\": \"https://gamepress.gg/dblegends/current-state-dragon-ball-legends-2nd-anniversary\",\r\n        \"body\": \"Dragon Ball Legends' AI is\u2026 quite frustrating, especially in the hardest levels. This Game's concept of difficulty is essentially based on making the enemies have very high Stats as well as perfect reaction times, so Players often have to resort to exploits that take advantage of the AI's deficiencies in order to best it.\"\r\n    },\r\n    {\r\n        \"title\": \"Dragon Ball Legends | DBZ Space\",\r\n        \"href\": \"https://legends.dbz.space/\",\r\n        \"body\": \"LEGENDS WEEKEND: 3 Days of Extra Fun at the End of Each Week! 04/18/2023 10:30 PM (PDT) ~ 12/31/2029 07:00 AM (PDT) Event.\"\r\n    },\r\n    {\r\n        \"title\": \"my current state with legends as of lately. : r/DragonballLegends - Reddit\",\r\n        \"href\": \"https://www.reddit.com/r/DragonballLegends/comments/y577dg/my_current_state_with_legends_as_of_lately/\",\r\n        \"body\": \"For context, I joined the game back during the second anniversary but dropped the game until a year ago. Ive been playing consistently ever since the\u2026\"\r\n    },\r\n    {\r\n        \"title\": \"[Gamepress]The Current State of Dragon Ball Legends - Reddit\",\r\n        \"href\": \"https://www.reddit.com/r/DragonballLegends/comments/hfo0vd/gamepressthe_current_state_of_dragon_ball_legends/\",\r\n        \"body\": \"Finally an article that provides correct criticism on today's state of the game. However you missed a tiny little point to address. That is the amount of various useless currencies like Z medals, Rush medals, rare medals because we get them in abundance and their shops have nothing really of value.\"\r\n    },\r\n    {\r\n        \"title\": \"The Current State of Db Legends\u2026|Dragonball Legends Discussion\",\r\n        \"href\": \"https://www.youtube.com/watch?v=wirP0mwA8zQ\",\r\n        \"body\": \"THE CURRENT STATE OF DB LEGENDS\u2026|DRAGONBALL LEGENDS DISCUSSION 2 views Aug 30, 2022 2 Dislike Share Save JB PLAYZ 3.95K subscribers Thank you all for the love and support on our journey to 5k...\"\r\n    },\r\n    {\r\n        \"title\": \"Wow...... The Current State of Dragon Ball Legends.... - YouTube\",\r\n        \"href\": \"https://www.youtube.com/watch?v=3Ai1z6qDjSA\",\r\n        \"body\": \"The Current State of Dragon Ball Legends.... DBZoom 120K subscribers Subscribe 640 11K views 10 months ago #chronocrystals #goku #dblegends I Post Here Daily Everything DB Legends So...\"\r\n    },\r\n    {\r\n        \"title\": \"Characters | Dragon Ball Legends | DBZ Space\",\r\n        \"href\": \"https://legends.dbz.space/characters/\",\r\n        \"body\": \"Android #18. Metal Cooler. Ultimate Gohan Absorbed Buu: Super. Bergamo. zenkaier. Super Saiyan Trunks (Adult) (Rage) Zamasu: Goku Black (Assist) Nuova Shenron. God of Destruction Beerus.\"\r\n    },\r\n    {\r\n        \"title\": \"Current State of Db Legends PvP! Beware! New Hack is not good news ...\",\r\n        \"href\": \"https://dragonball.fandom.com/f/p/4400000000000192096\",\r\n        \"body\": \"Current State of Db Legends PvP! Beware! New Hack is not good news! | Fandom Dragon Ball Wiki Explore Content Community About Us Dragon Ball Wiki 8,006 pages Explore Content Community About Us ALL POSTS Zeocx9040 \u00b7 8/16/2021 in Games Current State of Db Legends PvP! Beware! New Hack is not good news! UNLIMITED HEALTH HACK IN DRAGON BALL LEGENDS \ud83d\ude33!!\"\r\n    }\r\n]\r\n2023-04-23 21:45:22,664 INFO  THOUGHTS: I will use the 'browse_website' command to visit the Dragon Ball Legends subreddit and see what the community is saying about the current state of the game. This will help me identify specific areas that can be improved in the mod.\r\n2023-04-23 21:45:23,166 INFO REASONING: By visiting the subreddit, I can get a sense of what the community thinks about the current state of the game and what changes they would like to see. This information can be used to improve the mod and make it more appealing to players.\r\n2023-04-23 21:45:23,735 INFO PLAN: \r\n2023-04-23 21:45:23,783 INFO -  Use 'browse_website' to visit the Dragon Ball Legends subreddit\\n- Read through posts and comments to identify areas for improvement\\n- Use this information to make changes to the mod\r\n2023-04-23 21:45:24,231 INFO CRITICISM: I need to be careful not to get too caught up in reading through posts and comments and waste time. I should focus on identifying actionable insights that can be used to improve the mod.\r\n2023-04-23 21:45:24,738 INFO NEXT ACTION:  COMMAND = browse_website  ARGUMENTS = {'url': 'https://www.reddit.com/r/DragonballLegends/', 'question': 'areas for improvement in Dragon Ball Legends'}\r\n2023-04-23 21:45:33,267 INFO -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= \r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3054/reactions", "total_count": 1, "+1": 1, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/3054/timeline", "performed_via_github_app": null, "state_reason": null}