{"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1858", "repository_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT", "labels_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1858/labels{/name}", "comments_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1858/comments", "events_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1858/events", "html_url": "https://github.com/Significant-Gravitas/Auto-GPT/issues/1858", "id": 1669881619, "node_id": "I_kwDOJKSTjM5jiF8T", "number": 1858, "title": "No Module named 'Git' on Mac", "user": {"login": "PatVan77", "id": 124776920, "node_id": "U_kgDOB2_x2A", "avatar_url": "https://avatars.githubusercontent.com/u/124776920?v=4", "gravatar_id": "", "url": "https://api.github.com/users/PatVan77", "html_url": "https://github.com/PatVan77", "followers_url": "https://api.github.com/users/PatVan77/followers", "following_url": "https://api.github.com/users/PatVan77/following{/other_user}", "gists_url": "https://api.github.com/users/PatVan77/gists{/gist_id}", "starred_url": "https://api.github.com/users/PatVan77/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/PatVan77/subscriptions", "organizations_url": "https://api.github.com/users/PatVan77/orgs", "repos_url": "https://api.github.com/users/PatVan77/repos", "events_url": "https://api.github.com/users/PatVan77/events{/privacy}", "received_events_url": "https://api.github.com/users/PatVan77/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2023-04-16T11:32:54Z", "updated_at": "2023-04-26T22:56:20Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "### Duplicates\n\n- [X] I have searched the existing issues\n\n### Steps to reproduce \ud83d\udd79\n\nstart Autogpt from MAC Terminal (stable pull update from Github to this version\r\n\n\n### Current behavior \ud83d\ude2f\n\nWhen starting Autogpt on MAc console it seems to default to GIT for window\r\n\r\nHEAD Parse (ad7cefa10c0647feee85114d58559fcf83ba6743)\r\n\r\nCode behaviour:\r\n\r\n(base) patrickvanstokhem@MacBook-Pro-van-Patrick auto-gpt % python -m autogpt\r\nWeaviate not installed. Skipping import.\r\npymilvus not installed. Skipping import.\r\nWarning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.\r\nTraceback (most recent call last):\r\n  File \"/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/Users/patrickvanstokhem/Auto-GPT/autogpt/__main__.py\", line 4, in <module>\r\n    from autogpt.agent.agent import Agent\r\n  File \"/Users/patrickvanstokhem/Auto-GPT/autogpt/agent/__init__.py\", line 1, in <module>\r\n    from autogpt.agent.agent import Agent\r\n  File \"/Users/patrickvanstokhem/Auto-GPT/autogpt/agent/agent.py\", line 2, in <module>\r\n    from autogpt.app import execute_command, get_command\r\n  File \"/Users/patrickvanstokhem/Auto-GPT/autogpt/app.py\", line 26, in <module>\r\n    from autogpt.commands.git_operations import clone_repository\r\n  File \"/Users/patrickvanstokhem/Auto-GPT/autogpt/commands/git_operations.py\", line 2, in <module>\r\n    import git\r\nModuleNotFoundError: No module named 'git'\r\n(base) patrickvanstokhem@MacBook-Pro-van-Patrick auto-gpt % python -m autogpt\r\n Weaviate not installed. Skipping import.\r\npymilvus not installed. Skipping import.\r\nWarning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.\r\nTraceback (most recent call last):\r\n  File \"/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/__main__.py\", line 4, in <module>\r\n    from autogpt.agent.agent import Agent\r\n  File \"/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/agent/__init__.py\", line 1, in <module>\r\n    from autogpt.agent.agent import Agent\r\n  File \"/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/agent/agent.py\", line 2, in <module>\r\n    from autogpt.app import execute_command, get_command\r\n  File \"/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/app.py\", line 26, in <module>\r\n    from autogpt.commands.git_operations import clone_repository\r\n  File \"/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/commands/git_operations.py\", line 2, in <module>\r\n    import git\r\nModuleNotFoundError: No module named 'git'\r\n(base) patrickvanstokhem@MacBook-Pro-van-Patrick auto-gpt % python -m autogpt\r\nWeaviate not installed. Skipping import.\r\npymilvus not installed. Skipping import.\r\nWarning: The file 'AutoGpt.json' does not exist.Local memory would not be saved to a file.\r\nTraceback (most recent call last):\r\n  File \"/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/Users/patrickvanstokhem/opt/anaconda3/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/__main__.py\", line 4, in <module>\r\n    from autogpt.agent.agent import Agent\r\n  File \"/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/agent/__init__.py\", line 1, in <module>\r\n    from autogpt.agent.agent import Agent\r\n  File \"/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/agent/agent.py\", line 2, in <module>\r\n    from autogpt.app import execute_command, get_command\r\n  File \"/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/app.py\", line 26, in <module>\r\n    from autogpt.commands.git_operations import clone_repository\r\n  File \"/Users/patrickvanstokhem/Auto-GPT_NoGiFault/autogpt/commands/git_operations.py\", line 2, in <module>\r\n    import git\r\nModuleNotFoundError: No module named 'git'\n\n### Expected behavior \ud83e\udd14\n\nstart AutoGPT\n\n### Your prompt \ud83d\udcdd\n\n```yaml\r\n# Paste your prompt here\r\n```\r\n", "reactions": {"url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1858/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/Significant-Gravitas/Auto-GPT/issues/1858/timeline", "performed_via_github_app": null, "state_reason": null}